#!/usr/bin/env python3
"""
Test script to verify feedback generation behavior
Tests that feedback is only saved when actually generated by RealtimeAgent
"""
import asyncio
import sys
import os
import logging
from datetime import datetime

# Add the backend directory to Python path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Import logging setup FIRST
from core.logging import setup_logging
from services.conversation_flow import ConversationFlow
from services.persistence_service import persistence_service

# Setup enhanced logging
setup_logging(
    level="DEBUG",
    enable_file_logging=True,
    log_directory="logs",
    service_name="test_feedback_generation"
)

logger = logging.getLogger(__name__)


async def test_no_feedback_scenario():
    """Test that no feedback is saved when RealtimeAgent doesn't generate it"""
    logger.info("🧪 Testing NO FEEDBACK scenario")
    
    user_id = "test_user_no_feedback"
    
    try:
        # Create a ConversationFlow
        flow = ConversationFlow(user_id=user_id)
        logger.info(f"✅ ConversationFlow initialized for user: {user_id}")
        
        # Create a mock conversation summary WITHOUT feedback
        mock_conversation_summary = {
            "session_id": flow.session_id,
            "conversation_text": "User: Hello\nAI: Hi there!\nUser: Bye\nAI: Goodbye!",
            "messages": [
                {"role": "user", "content": "Hello", "timestamp": "2025-07-29T17:00:00"},
                {"role": "assistant", "content": "Hi there!", "timestamp": "2025-07-29T17:00:01"},
                {"role": "user", "content": "Bye", "timestamp": "2025-07-29T17:00:02"},
                {"role": "assistant", "content": "Goodbye!", "timestamp": "2025-07-29T17:00:03"}
            ],
            "duration_seconds": 30.0,
            "conversation_json": {
                "session_id": flow.session_id,
                "message_count": 4,
                "messages": [
                    {"role": "user", "content": "Hello", "timestamp": "2025-07-29T17:00:00", "order": 1},
                    {"role": "assistant", "content": "Hi there!", "timestamp": "2025-07-29T17:00:01", "order": 2},
                    {"role": "user", "content": "Bye", "timestamp": "2025-07-29T17:00:02", "order": 3},
                    {"role": "assistant", "content": "Goodbye!", "timestamp": "2025-07-29T17:00:03", "order": 4}
                ]
            }
        }
        
        logger.info("📝 Testing feedback generation with NO AI feedback...")
        
        # Test the _generate_feedback method directly
        feedback_result = await flow._generate_feedback(mock_conversation_summary)
        
        if feedback_result is None:
            logger.info("✅ SUCCESS: _generate_feedback returned None (no fallback)")
        else:
            logger.error(f"❌ FAILURE: _generate_feedback returned: {feedback_result}")
            return False
        
        # Test the persistence service directly with None feedback
        logger.info("🔄 Testing persistence service with None feedback...")
        
        # Test that persistence service handles None feedback correctly
        # Generate a valid session_id since flow.session_id is None
        import uuid
        test_session_id = str(uuid.uuid4())
        
        try:
            result = await persistence_service.save_complete_conversation(
                session_id=test_session_id,
                user_id=user_id,
                conversation_json=mock_conversation_summary["conversation_json"],
                feedback_data=None,  # This is the key test - None feedback
                duration_seconds=30,
                agent_type="realtime",
                mode="free_topic"
            )
            
            logger.info(f"📊 Persistence result: {result['summary']}")
            
            # Check that no feedback items were created
            session_summary = await persistence_service.get_session_summary(test_session_id)
            feedback_count = len(session_summary.get("feedback_items", []))
            
            if feedback_count == 0:
                logger.info("✅ SUCCESS: No feedback items saved to database when feedback_data=None")
            else:
                logger.error(f"❌ FAILURE: {feedback_count} feedback items found in database despite None feedback")
                return False
                
        except Exception as e:
            logger.error(f"❌ FAILURE: Persistence service failed with None feedback: {e}")
            return False
        
        logger.info("🎉 ALL TESTS PASSED: No feedback generated or saved when not provided by RealtimeAgent")
        return True
        
    except Exception as e:
        logger.error(f"❌ Test failed with error: {e}")
        return False


async def test_with_feedback_scenario():
    """Test that feedback IS saved when RealtimeAgent generates it"""
    logger.info("🧪 Testing WITH FEEDBACK scenario")
    
    user_id = "test_user_with_feedback"
    
    try:
        # Create a ConversationFlow
        flow = ConversationFlow(user_id=user_id)
        logger.info(f"✅ ConversationFlow initialized for user: {user_id}")
        
        # Create a mock conversation summary WITH feedback
        mock_feedback_message = {
            "role": "assistant",
            "content": '{"feedback_type": "conversation_analysis", "overall_score": 8.5, "summary": "Good conversation with room for improvement", "pillars": {"pronunciation": {"score": 8.0, "feedback": "Clear pronunciation", "examples": [], "suggestions": []}, "fluency": {"score": 7.5, "feedback": "Good flow", "examples": [], "suggestions": []}, "grammar": {"score": 8.5, "feedback": "Excellent grammar", "examples": [], "suggestions": []}, "expressions": {"score": 7.0, "feedback": "Basic expressions used", "examples": [], "suggestions": []}, "vocabulary": {"score": 8.0, "feedback": "Good vocabulary range", "examples": [], "suggestions": []}, "comprehension": {"score": 9.0, "feedback": "Excellent understanding", "examples": [], "suggestions": []}}}',
            "timestamp": "2025-07-29T17:00:04",
            "order": 5
        }
        
        mock_conversation_summary = {
            "session_id": flow.session_id,
            "conversation_text": "User: Hello\nAI: Hi there!\nUser: Bye\nAI: Goodbye!",
            "messages": [
                {"role": "user", "content": "Hello", "timestamp": "2025-07-29T17:00:00"},
                {"role": "assistant", "content": "Hi there!", "timestamp": "2025-07-29T17:00:01"},
                {"role": "user", "content": "Bye", "timestamp": "2025-07-29T17:00:02"},
                {"role": "assistant", "content": "Goodbye!", "timestamp": "2025-07-29T17:00:03"},
                mock_feedback_message
            ],
            "duration_seconds": 35.0,
            "conversation_json": {
                "session_id": flow.session_id,
                "message_count": 5,
                "messages": [
                    {"role": "user", "content": "Hello", "timestamp": "2025-07-29T17:00:00", "order": 1},
                    {"role": "assistant", "content": "Hi there!", "timestamp": "2025-07-29T17:00:01", "order": 2},
                    {"role": "user", "content": "Bye", "timestamp": "2025-07-29T17:00:02", "order": 3},
                    {"role": "assistant", "content": "Goodbye!", "timestamp": "2025-07-29T17:00:03", "order": 4},
                    mock_feedback_message
                ]
            }
        }
        
        logger.info("📝 Testing feedback generation WITH AI feedback...")
        
        # Test the _generate_feedback method directly
        feedback_result = await flow._generate_feedback(mock_conversation_summary)
        
        if feedback_result is not None and feedback_result.get("source") == "realtime_agent":
            logger.info("✅ SUCCESS: _generate_feedback returned real AI feedback")
            logger.info(f"   📊 Overall score: {feedback_result.get('overall_score')}")
            logger.info(f"   📝 Summary: {feedback_result.get('summary')}")
        else:
            logger.error(f"❌ FAILURE: _generate_feedback returned: {feedback_result}")
            return False
        
        logger.info("🎉 WITH FEEDBACK TEST PASSED: Real AI feedback detected and processed")
        return True
        
    except Exception as e:
        logger.error(f"❌ Test failed with error: {e}")
        return False


async def main():
    """Run all feedback generation tests"""
    logger.info("🚀 Starting Feedback Generation Tests")
    logger.info("=" * 60)
    
    # Test 1: No feedback scenario
    test1_result = await test_no_feedback_scenario()
    
    print("\n" + "=" * 60)
    
    # Test 2: With feedback scenario  
    test2_result = await test_with_feedback_scenario()
    
    print("\n" + "=" * 60)
    
    # Summary
    if test1_result and test2_result:
        logger.info("🎉 ALL TESTS PASSED!")
        logger.info("✅ Feedback system working correctly:")
        logger.info("   • No fallback feedback when RealtimeAgent doesn't provide it")
        logger.info("   • Real feedback processed when RealtimeAgent provides it")
    else:
        logger.error("❌ SOME TESTS FAILED!")
        logger.error(f"   Test 1 (No Feedback): {'PASS' if test1_result else 'FAIL'}")
        logger.error(f"   Test 2 (With Feedback): {'PASS' if test2_result else 'FAIL'}")


if __name__ == "__main__":
    asyncio.run(main())
