#!/usr/bin/env python3
"""
Test script to verify realtime feedback generation
This test simulates a longer conversation with the RealtimeAgent and verifies
that feedback is properly generated and returned when ending the conversation.
"""
import asyncio
import sys
import os
import logging
import json
from datetime import datetime

# Add the backend directory to Python path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Import logging setup FIRST
from core.logging import setup_logging, get_logger
from services.conversation_flow import ConversationFlow
from services.conversation_service import ConversationService
from services.openai_service import OpenAIService
from core.colors import colorize, Colors

# Setup enhanced logging
setup_logging(
    level="DEBUG",
    enable_file_logging=True,
    log_directory="logs",
    service_name="test_realtime_feedback"
)

logger = get_logger(__name__)


async def test_realtime_feedback_generation():
    """
    Test that feedback is properly generated by the RealtimeAgent
    by simulating a longer conversation with multiple turns
    """
    logger.info("🧪 Testing REALTIME FEEDBACK generation")
    print("\n" + "=" * 80)
    print("🧪 REALTIME FEEDBACK GENERATION TEST")
    print("=" * 80)
    
    user_id = "test_user_realtime_feedback"
    
    try:
        # Create services
        conversation_service = ConversationService()
        openai_service = OpenAIService()
        
        # Create a ConversationFlow
        flow = ConversationFlow(user_id=user_id)
        logger.info(f"✅ ConversationFlow initialized for user: {user_id}")
        print(f"✅ ConversationFlow initialized for user: {user_id}")
        
        # Start the conversation
        session_id = await flow.start_conversation()
        logger.info(f"✅ Started conversation with session ID: {session_id}")
        print(f"✅ Started conversation with session ID: {session_id}")
        
        # Simulate a longer conversation with multiple turns and AI responses
        # This will give the model more context to generate meaningful feedback
        conversation_turns = [
            # Turn 1 - Introduction
            {"role": "user", "content": "Hello! I'm trying to practice my English. Can you help me improve my speaking skills?"},
            {"role": "assistant", "content": "Hello! I'd be happy to help you practice your English speaking skills. What specific areas would you like to work on today?"},
            
            # Turn 2 - Past tense errors
            {"role": "user", "content": "Yesterday I goed to the store and buyed some food. I eated lunch with my friend. We haved a good time."},
            {"role": "assistant", "content": "I understand. Let's practice the past tense together. The correct forms would be: 'went' instead of 'goed', 'bought' instead of 'buyed', 'ate' instead of 'eated', and 'had' instead of 'haved'. Could you try that sentence again with these corrections?"},
            
            # Turn 3 - Preposition errors
            {"role": "user", "content": "I went to the store and bought some food. I also have trouble with prepositions. I arrived to the airport at time. I was in the bus. The book is above the table."},
            {"role": "assistant", "content": "Great job with the past tense! For prepositions, we would say 'arrived at the airport on time', 'on the bus' (not 'in'), and 'on the table' (not 'above'). Prepositions can be tricky because they don't always translate directly between languages."},
            
            # Turn 4 - Vocabulary practice
            {"role": "user", "content": "I want to improve my vocabulary. Can you teach me words to describe the weather? In my country it's very hot in summer."},
            {"role": "assistant", "content": "I'd be happy to help with weather vocabulary! Here are some useful terms: 'scorching' (extremely hot), 'humid' (hot and damp), 'mild' (neither hot nor cold), 'chilly' (slightly cold), 'freezing' (very cold). For rain, we use words like 'drizzle', 'downpour', and 'shower'. Can you describe the weather in your country using some of these words?"},
            
            # Turn 5 - Student attempt with vocabulary
            {"role": "user", "content": "In summer, it's scorching and very humid. Sometimes we have downpours in the afternoon. In winter, it's not freezing but sometimes chilly in the morning."},
            {"role": "assistant", "content": "Excellent use of the new vocabulary! Your description gives me a clear picture of the weather in your country - hot, humid summers with afternoon rainstorms, and mild winters with cool mornings. Your sentence structure was also very good."},
            
            # Turn 6 - Closing the conversation
            {"role": "user", "content": "Thank you for helping me practice. I learned many new words and fixed my grammar mistakes. I will practice more. Goodbye!"},
            {"role": "assistant", "content": "You're very welcome! You've made great progress in our conversation. Your English is already quite good, and with continued practice, especially with past tense verbs and prepositions, you'll keep improving. Feel free to practice again anytime. Goodbye and good luck with your studies!"}
        ]
        
        # Process each turn in the conversation
        message_count = len(conversation_turns)
        for i, message in enumerate(conversation_turns, 1):
            logger.info(f"💬 Processing conversation turn {i}/{message_count}")
            print(f"💬 Turn {i}/{message_count}: {message['content'][:50]}...")
            
            # Add the message to the agent's session state
            if flow.realtime_agent and flow.realtime_agent.session_state:
                # Add the message to the session state
                flow.realtime_agent.session_state.messages.append(message)
                
                # Update transcript for backward compatibility based on role
                if message['role'] == 'user':
                    flow.realtime_agent.session_state.user_transcript += f"{message['content']}\n"
                else:  # assistant
                    flow.realtime_agent.session_state.ai_transcript += f"{message['content']}\n"
            
            # Short delay between turns
            await asyncio.sleep(1)
        
        # Explicitly request feedback generation
        logger.info("🔄 Requesting feedback generation...")
        print("\n🔄 Requesting feedback generation...")
        
        # Add a final user message that should trigger feedback generation
        final_message = {
            "role": "user",
            "content": "This was a great conversation. I learned a lot about past tense, prepositions, and weather vocabulary. Thank you for your help! Goodbye!"
        }
        
        if flow.realtime_agent and flow.realtime_agent.session_state:
            flow.realtime_agent.session_state.messages.append(final_message)
            flow.realtime_agent.session_state.user_transcript += f"{final_message['content']}\n"
            logger.info("Added final goodbye message to trigger feedback")
        
        # Simulate conversation termination with explicit feedback request
        if flow.realtime_agent:
            # Directly call the termination handler
            await flow.realtime_agent._handle_conversation_termination()
            logger.info("⏳ Waiting for feedback generation to complete...")
            print("⏳ Waiting for feedback generation to complete...")
            
            # Give the model more time to generate feedback
            logger.info("Waiting 20 seconds for feedback generation...")
            await asyncio.sleep(20)
            
            # Check if feedback was generated - try multiple times with increasing wait periods
            max_attempts = 3
            for attempt in range(1, max_attempts + 1):
                if flow.realtime_agent.conversation_feedback:
                    logger.info("✅ Feedback successfully generated!")
                    print(f"✅ Feedback successfully generated on attempt {attempt}!")
                    print("=" * 60)
                    
                    # Get feedback data
                    feedback_summary = flow.realtime_agent.conversation_feedback.get('resumen', 'N/A')
                    feedback_content = flow.realtime_agent.conversation_feedback.get('feedback', 'N/A')
                    feedback_timestamp = flow.realtime_agent.conversation_feedback.get('timestamp', 'N/A')
                    
                    # Log detailed feedback information
                    print(f"📋 Feedback summary ({len(feedback_summary)} chars): {feedback_summary}")
                    print(f"💬 Feedback content ({len(feedback_content)} chars): {feedback_content}")
                    print(f"📅 Feedback timestamp: {feedback_timestamp}")
                    print("=" * 60)
                    
                    # Validate feedback quality
                    if len(feedback_summary) < 20 or len(feedback_content) < 50:
                        logger.warning("⚠️ Feedback generated but content is suspiciously short")
                        print("⚠️ Feedback generated but content is suspiciously short")
                    
                    return True
                else:
                    wait_time = attempt * 10  # Increase wait time with each attempt
                    logger.info(f"⏳ Attempt {attempt}/{max_attempts}: No feedback yet, waiting {wait_time} more seconds...")
                    print(f"⏳ Attempt {attempt}/{max_attempts}: No feedback yet, waiting {wait_time} more seconds...")
                    await asyncio.sleep(wait_time)
            
            # If we get here, all attempts failed
            logger.error("❌ No feedback was generated after multiple attempts")
            print("❌ No feedback was generated after multiple attempts")
            return False
        
        logger.error("❌ RealtimeAgent not properly initialized")
        print("❌ RealtimeAgent not properly initialized")
        return False
        
    except Exception as e:
        logger.error(f"❌ Test failed with error: {str(e)}")
        print(f"❌ Test failed with error: {str(e)}")
        import traceback
        logger.error(traceback.format_exc())
        return False


async def main():
    """Run the realtime feedback generation test"""
    logger.info("🚀 Starting Realtime Feedback Generation Test")
    print("🚀 Starting Realtime Feedback Generation Test")
    
    result = await test_realtime_feedback_generation()
    
    print("\n" + "=" * 80)
    if result:
        logger.info("🎉 TEST PASSED: Realtime feedback generation is working!")
        print("🎉 TEST PASSED: Realtime feedback generation is working!")
    else:
        logger.error("❌ TEST FAILED: Realtime feedback generation is not working")
        print("❌ TEST FAILED: Realtime feedback generation is not working")
    print("=" * 80)


if __name__ == "__main__":
    print("🧪 REALTIME FEEDBACK GENERATION TEST")
    print("=" * 80)
    print("This test will:")
    print("1. 🔄 Initialize a RealtimeAgent")
    print("2. 💬 Simulate a conversation with multiple turns")
    print("3. 🛑 Request feedback generation")
    print("4. ✅ Verify that feedback is generated")
    print("=" * 80)
    
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\n⚠️ Test interrupted by user")
    except Exception as e:
        print(f"\n❌ Unexpected error: {str(e)}")
